/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Arbol02 = (props) => {
  const { nodes, materials } = useGLTF("./models/vegetation/Arbol02.glb");

  const furTextureWood = useTexture("./textures/VG/Arbol02.jpg");
  furTextureWood.flipY = false;
  furTextureWood.colorSpace = THREE.SRGBColorSpace;

  // Floor 01
  const furWall = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: furTextureWood,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [furTextureWood]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arbol02Web.geometry}
        // material={materials["Material_0.038"]}
        material={furWall}
        position={[-54.833, 22.396, 30.87]}
        rotation={[Math.PI, -0.61, Math.PI]}
        scale={2.567}
      />
    </group>
  );
};

useGLTF.preload("./models/vegetation/Arbol02.glb");

export default Arbol02;
