/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Arbol06 = (props) => {
  const { nodes, materials } = useGLTF("./models/vegetation/Arbol06.glb");

  const furTextureWood = useTexture("./textures/VG/Arbol06.jpg");
  furTextureWood.flipY = false;
  furTextureWood.colorSpace = THREE.SRGBColorSpace;

  // Floor 01
  const furWall = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: furTextureWood,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [furTextureWood]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arbol06Web.geometry}
        // material={materials["Material_0.028"]}
        material={furWall}
        position={[23.126, 21.691, 74]}
        rotation={[Math.PI, -0.159, Math.PI]}
        scale={2.605}
      />
    </group>
  );
};

useGLTF.preload("./models/vegetation/Arbol06.glb");

export default Arbol06;
