/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Arbustos02 = (props) => {
  const { nodes, materials } = useGLTF("./models/vegetation/Arbustos02.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-84.874, 31.667, 26.159]}
        rotation={[-Math.PI, 1.031, -Math.PI]}
        scale={0.752}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.temp_meshply259.geometry}
          material={materials["Material_0.027"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.temp_meshply259_1.geometry}
          material={materials["Material_0.026"]}
        />
      </group>
    </group>
  );
};

useGLTF.preload("./models/vegetation/Arbustos02.glb");

export default Arbustos02;
