/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Arbustos01 = (props) => {
  const { nodes, materials } = useGLTF("./models/vegetation/Arbustos01.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arbustos01Web.geometry}
        material={materials["Material_0.025"]}
        position={[22.032, 20.763, 57.049]}
        rotation={[0.049, 0.86, -0.065]}
        scale={1.829}
      />
    </group>
  );
};

useGLTF.preload("./models/vegetation/Arbustos01.glb");

export default Arbustos01;
