/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Cactus01 = (props) => {
  const { nodes, materials } = useGLTF("./models/vegetation/Cactus01.glb");

  const furTextureWood = useTexture("./textures/VG/Cactus01.jpg");
  furTextureWood.flipY = false;
  furTextureWood.colorSpace = THREE.SRGBColorSpace;

  // Floor 01
  const furWall = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: furTextureWood,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [furTextureWood]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cactus01Web.geometry}
        // material={materials["Material_0.032"]}
        material={furWall}
        position={[-67.014, 22.815, 72.04]}
        rotation={[0, -0.914, 0]}
        scale={1.902}
      />
    </group>
  );
};

useGLTF.preload("./models/vegetation/Cactus01.glb");

export default Cactus01;
