/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Palmera05 = (props) => {
  const { nodes, materials } = useGLTF("./models/vegetation/Palmera05.glb");

  const furTextureWood = useTexture("./textures/VG/Palmera05.jpg");
  furTextureWood.flipY = false;
  furTextureWood.colorSpace = THREE.SRGBColorSpace;

  // Floor 01
  const furWall = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: furTextureWood,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [furTextureWood]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Palmera05Web.geometry}
        // material={materials["Material_0.029"]}
        material={furWall}
        position={[156.269, 20.125, 72.897]}
        rotation={[0, 1.004, 0]}
        scale={3.512}
      />
    </group>
  );
};

useGLTF.preload("./models/vegetation/Palmera05.glb");

export default Palmera05;
