/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Palmera11 = (props) => {
  const { nodes, materials } = useGLTF("./models/vegetation/Palmera11.glb");

  const furTextureWood = useTexture("./textures/VG/Palmera11.jpg");
  furTextureWood.flipY = false;
  furTextureWood.colorSpace = THREE.SRGBColorSpace;

  // Floor 01
  const furWall = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: furTextureWood,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [furTextureWood]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Palmera11Web.geometry}
        // material={materials["Material_0.033"]}
        material={furWall}
        position={[148.424, 26.024, 32.796]}
        scale={3.673}
      />
    </group>
  );
};

useGLTF.preload("./models/vegetation/Palmera11.glb");

export default Palmera11;
