/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Palmera02 = (props) => {
  const { nodes, materials } = useGLTF("./models/vegetation/Palmera02.glb");

  const furTextureWood = useTexture("./textures/VG/Palmera02.jpg");
  furTextureWood.flipY = false;
  furTextureWood.colorSpace = THREE.SRGBColorSpace;

  // Floor 01
  const furWall = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: furTextureWood,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [furTextureWood]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Palmera02Web.geometry}
        // material={materials["Material_0.031"]}
        material={furWall}
        position={[108.002, 20.371, 73.35]}
        rotation={[-Math.PI, 0.535, -Math.PI]}
        scale={4.186}
      />
    </group>
  );
};

useGLTF.preload("./models/vegetation/Palmera02.glb");

export default Palmera02;
