/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Palmera04 = (props) => {
  const { nodes, materials } = useGLTF("./models/vegetation/Palmera04.glb");

  const furTextureWood = useTexture("./textures/VG/Palmera04.jpg");
  furTextureWood.flipY = false;
  furTextureWood.colorSpace = THREE.SRGBColorSpace;

  // Floor 01
  const furWall = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: furTextureWood,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [furTextureWood]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Palmera04Web.geometry}
        // material={materials["Material_0.030"]}
        material={furWall}
        position={[-136.973, 25.119, 76.401]}
        rotation={[Math.PI, -1.3, Math.PI]}
        scale={4.931}
      />
    </group>
  );
};

useGLTF.preload("./models/vegetation/Palmera04.glb");

export default Palmera04;
