/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Agua.glb 
*/

import React, { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

const Agua = (props) => {
  const { nodes, materials } = useGLTF('./models/Agua.glb')


  // Fix tonos y espacio de color
  useEffect(() => {
    Object.values(materials).forEach((mat) => {
      if (!mat) return

      // 1. Evitar tone mapping
      mat.toneMapped = false

      // 2. Forzar sRGB
      mat.colorSpace = THREE.SRGBColorSpace

      // 3. Si tiene texturas, corregirlas una por una
      if (mat.map) mat.map.colorSpace = THREE.SRGBColorSpace
      if (mat.emissiveMap) mat.emissiveMap.colorSpace = THREE.SRGBColorSpace
      if (mat.roughnessMap) mat.roughnessMap.colorSpace = THREE.SRGBColorSpace
      if (mat.normalMap) mat.normalMap.colorSpace = THREE.SRGBColorSpace
      if (mat.metalnessMap) mat.metalnessMap.colorSpace = THREE.SRGBColorSpace
      if (mat.aoMap) mat.aoMap.colorSpace = THREE.SRGBColorSpace

      mat.needsUpdate = true
    })
  }, [materials])



  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pools.geometry} material={materials.Agua} position={[4.989, 20.991, 60.339]} rotation={[0.005, -0.349, -1.569]} />
    </group>
  )
}

useGLTF.preload('./models/Agua.glb')

export default Agua
