/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Amenities.glb 
*/

import React, { useMemo } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'

const Amenities = (props) => {
  const { nodes, materials } = useGLTF('./models/Amenities.glb')

  const amTextureFloor01 = useTexture('./textures/AM/AM_Floor01.jpg')
  amTextureFloor01.flipY = false
  amTextureFloor01.colorSpace = THREE.SRGBColorSpace

  const amTextureFloor02 = useTexture('./textures/AM/AM_Floor02.jpg')
  amTextureFloor02.flipY = false
  amTextureFloor02.colorSpace = THREE.SRGBColorSpace

  const amTextureFrames = useTexture('./textures/AM/AM_Frames.jpg')
  amTextureFrames.flipY = false
  amTextureFrames.colorSpace = THREE.SRGBColorSpace

  const amTextureWalls = useTexture('./textures/AM/AM_Walls.jpg')
  amTextureWalls.flipY = false
  amTextureWalls.colorSpace = THREE.SRGBColorSpace

  const amTextureWood = useTexture('./textures/AM/AM_Wood.jpg')
  amTextureWood.flipY = false
  amTextureWood.colorSpace = THREE.SRGBColorSpace


  // Floor 01
  const amFloor01 = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: amTextureFloor01,
      toneMapped: false            // prevent threejs from washing colors
    })
  }, [amTextureFloor01])

  // Floor 01
  const amFloor02 = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: amTextureFloor02,
      toneMapped: false            // prevent threejs from washing colors
    })
  }, [amTextureFloor02])

  // Floor 01
  const amFrames = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: amTextureFrames,
      toneMapped: false            // prevent threejs from washing colors
    })
  }, [amTextureFrames])

  // Floor 01
  const amWalls = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: amTextureWalls,
      toneMapped: false            // prevent threejs from washing colors
    })
  }, [amTextureWalls])

  // Floor 01
  const amWood = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: amTextureWood,
      toneMapped: false            // prevent threejs from washing colors
    })
  }, [amTextureWood])



  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.AMW_Floor01.geometry} 
        // material={materials.Concrete}
        material={ amFloor01 }
      >
        {/* <meshBasicMaterial map={amTextureFloor01} /> */}
      </mesh>  
      <mesh 
        geometry={nodes.AMW_Floor02.geometry} 
        // material={materials.Concrete}
        material={ amFloor02 }
      >
        {/* <meshBasicMaterial map={amTextureFloor02} /> */}
      </mesh>  
      <mesh 
        geometry={nodes.AMW_Frames.geometry} 
        // material={materials.Wood}
        material={ amFrames }
      >
        {/* <meshBasicMaterial map={amTextureFrames} /> */}
      </mesh>  
      <mesh 
        geometry={nodes.AMW_Walls.geometry} 
        // material={materials.Wall}
        material={ amWalls }
      >
        {/* <meshBasicMaterial map={amTextureWalls} /> */}
      </mesh>  
      <mesh 
        geometry={nodes.AMW_Wood.geometry} 
        // material={materials.Wood}
        material={ amWood }
      >
        {/* <meshBasicMaterial map={amTextureWood} /> */}
      </mesh>  
    </group>
  )
}

useGLTF.preload('./models/Amenities.glb')

export default Amenities
