/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Basamento.glb 
*/

import React, { useMemo } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'

const Basamento = (props) => {
  const { nodes, materials } = useGLTF('./models/Basamento.glb')

  const baTexture = useTexture('./textures/BA/BA_Plataformas.jpg')
  baTexture.flipY = false
  baTexture.colorSpace = THREE.SRGBColorSpace

  const baPlataformas = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: baTexture,
      toneMapped: false            // prevent threejs from washing colors
    })
  }, [baTexture])

  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.Object_1001.geometry} 
        // material={materials.Wall} 
        material={ baPlataformas }
      >

      </mesh>
    </group>
  )
}

useGLTF.preload('./models/Basamento.glb')

export default Basamento
