/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Casona01.glb 
*/

import React, { useMemo } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'

const Casona01 = (props) => {
  const { nodes, materials } = useGLTF('./models/Casona01.glb')

  const c01TextureFloor01 = useTexture('./textures/C01/C01_Floor01.jpg')
  c01TextureFloor01.flipY = false
  c01TextureFloor01.colorSpace = THREE.SRGBColorSpace

  const c01TextureFloor02 = useTexture('./textures/C01/C01_Floor02.jpg')
  c01TextureFloor02.flipY = false
  c01TextureFloor02.colorSpace = THREE.SRGBColorSpace

  const c01TextureFloor03 = useTexture('./textures/C01/C01_Floor03.jpg')
  c01TextureFloor03.flipY = false
  c01TextureFloor03.colorSpace = THREE.SRGBColorSpace

  const c01TextureFrames = useTexture('./textures/C01/C01_Frames.jpg')
  c01TextureFrames.flipY = false
  c01TextureFrames.colorSpace = THREE.SRGBColorSpace

  const c01TextureRoof = useTexture('./textures/C01/C01_Roof.jpg')
  c01TextureRoof.flipY = false
  c01TextureRoof.colorSpace = THREE.SRGBColorSpace

  const c01TextureWall = useTexture('./textures/C01/C01_Wall.jpg')
  c01TextureWall.flipY = false
  c01TextureWall.colorSpace = THREE.SRGBColorSpace

  const c01TextureWood = useTexture('./textures/C01/C01_Wood.jpg')
  c01TextureWood.flipY = false
  c01TextureWood.colorSpace = THREE.SRGBColorSpace



  // Floor 01
  const c01Floor01 = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c01TextureFloor01,
      toneMapped: false            // prevent threejs from washing colors
    })
  }, [c01TextureFloor01])

    // Floor 01
  const c01Floor02 = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c01TextureFloor02,
      toneMapped: false            // prevent threejs from washing colors
    })
  }, [c01TextureFloor02])

  // Floor 01
  const c01Floor03 = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c01TextureFloor03,
      toneMapped: false            // prevent threejs from washing colors
    })
  }, [c01TextureFloor03])

  // Floor 01
  const c01Frames = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c01TextureFrames,
      toneMapped: false            // prevent threejs from washing colors
    })
  }, [c01TextureFrames])

  // Floor 01
  const c01Roof = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c01TextureRoof,
      toneMapped: false            // prevent threejs from washing colors
    })
  }, [c01TextureRoof])

  // Floor 01
  const c01Wall = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c01TextureWall,
      toneMapped: false            // prevent threejs from washing colors
    })
  }, [c01TextureWall])

  // Floor 01
  const c01Wood = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c01TextureWood,
      toneMapped: false            // prevent threejs from washing colors
    })
  }, [c01TextureWood])





  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.C01W_Roof.geometry} 
        // material={materials.Wood} 
        material={ c01Roof }
      >
        {/* <meshBasicMaterial map={ c01TextureRoof } /> */}
      </mesh>

      <mesh 
        geometry={nodes.C01W_Floor01.geometry} 
        // material={materials.Concrete} 
        material={ c01Floor01 }
      >
        {/* <meshBasicMaterial map={ c01TextureFloor01 } /> */}
      </mesh>

      <mesh 
        geometry={nodes.C01W_Floor02.geometry} 
        // material={materials.Concrete} 
        material={ c01Floor02 }
      >
        {/* <meshBasicMaterial map={ c01TextureFloor02 } /> */}
      </mesh>

      <mesh 
        geometry={nodes.C01W_Floor03.geometry} 
        // material={materials.Concrete}
        material={ c01Floor03 }
      >
        {/* <meshBasicMaterial map={ c01TextureFloor03 } /> */}
      </mesh>

      <mesh 
        geometry={nodes.C01W_Frames.geometry} 
        // material={materials.Wood} 
        material={ c01Frames }
      >
        {/* <meshBasicMaterial map={ c01TextureFrames } /> */}
      </mesh>

      <mesh 
        geometry={nodes.C01W_Wall01.geometry} 
        // material={materials.Wall} 
        material={ c01Wall }
      >
        {/* <meshBasicMaterial map={ c01TextureWall } /> */}
      </mesh>

      <mesh 
        geometry={nodes.C01W_Wood.geometry} 
        // material={materials.Wood} 
        material={ c01Wood }
      >
        {/* <meshBasicMaterial map={ c01TextureWood } /> */}
      </mesh>

    </group>
  )
}

useGLTF.preload('./models/Casona01.glb')

export default Casona01
