/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Casona04.glb 
*/

import React, { useMemo } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as   THREE from 'three'

const Casona04 = (props) => {
  const { nodes, materials } = useGLTF('./models/Casona04.glb')

  const c04TextureFloor02 = useTexture('./textures/C04/CA04_02_Floor02.jpg')
  c04TextureFloor02.flipY = false
  c04TextureFloor02.colorSpace = THREE.SRGBColorSpace

  const c04TextureFloor = useTexture('./textures/C04/CA04_02_Floor.jpg')
  c04TextureFloor.flipY = false
  c04TextureFloor.colorSpace = THREE.SRGBColorSpace

  const c04TextureRoof = useTexture('./textures/C04/CA04_02_Roof.jpg')
  c04TextureRoof.flipY = false
  c04TextureRoof.colorSpace = THREE.SRGBColorSpace

  const c04TextureWall = useTexture('./textures/C04/CA04_02_Wall.jpg')
  c04TextureWall.flipY = false
  c04TextureWall.colorSpace = THREE.SRGBColorSpace

  const c04TextureWood = useTexture('./textures/C04/CA04_02_Wood.jpg')
  c04TextureWood.flipY = false
  c04TextureWood.colorSpace = THREE.SRGBColorSpace



// Floor 01
const matFloor02 = useMemo(() => {
  return new THREE.MeshStandardMaterial({
    map: c04TextureFloor02,
    toneMapped: false
  })
}, [c04TextureFloor02])

// Floor 02
const matFloor = useMemo(() => {
  return new THREE.MeshStandardMaterial({
    map: c04TextureFloor,
    toneMapped: false
  })
}, [c04TextureFloor])

// Roof
const matRoof = useMemo(() => {
  return new THREE.MeshStandardMaterial({
    map: c04TextureRoof,
    toneMapped: false,
  })
}, [c04TextureRoof])

// Wall
const matWall = useMemo(() => {
  return new THREE.MeshStandardMaterial({
    map: c04TextureWall,
    toneMapped: false,
  })
}, [c04TextureWall])

// Wood
const matWood = useMemo(() => {
  return new THREE.MeshStandardMaterial({
    map: c04TextureWood,
    toneMapped: false,
  })
}, [c04TextureWood])




  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.CA04_02_Floor02.geometry} 
        // material={materials.Concrete} 
        material={matFloor02} 
      >

      </mesh>
      <mesh 
        geometry={nodes.CA04_02_Floor.geometry} 
        // material={materials.Concrete} 
        material={matFloor} 
      >

      </mesh>
      <mesh 
        geometry={nodes.CA04_02_Roof.geometry} 
        // material={materials.Wall} 
        material={matRoof} 
      >

      </mesh>
      <mesh 
        geometry={nodes.CA04_02_Wall.geometry} 
        // material={materials.Wall} 
        material={matWall} 
      >

      </mesh>
      <mesh 
        geometry={nodes.CA04_02_Wood.geometry} 
        // material={materials.Wood} 
        material={matWood} 
      >

      </mesh>
    </group>
  )
}

useGLTF.preload('./models/Casona04.glb')

export default Casona04
