/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Casona02.glb 
*/

import React, { useMemo } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'


const Casona02 = (props) => {
  const { nodes, materials } = useGLTF('./models/Casona02.glb')


  // // Creamos el material solo una vez
  // const whiteTransparentMat = useMemo(() => {
  //   return new THREE.MeshStandardMaterial({
  //     color: '#FFFEF7',
  //     transparent: true,
  //     opacity: 0.8,
  //     // depthWrite: true,
  //   })
  // }, [])



  const c02TextureConcrete = useTexture('./textures/C02/C02_Concrete.jpg')
  c02TextureConcrete.flipY = false
  c02TextureConcrete.colorSpace = THREE.SRGBColorSpace

  const c02TextureFloor = useTexture('./textures/C02/C02_Floor.jpg')
  c02TextureFloor.flipY = false
  c02TextureFloor.colorSpace = THREE.SRGBColorSpace

  const c02TextureFrames = useTexture('./textures/C02/C02_Frames.jpg')
  c02TextureFrames.flipY = false
  c02TextureFrames.colorSpace = THREE.SRGBColorSpace

  const c02TextureWall = useTexture('./textures/C02/C02_Wall.jpg')
  c02TextureWall.flipY = false
  c02TextureWall.colorSpace = THREE.SRGBColorSpace

  const c02TextureWood = useTexture('./textures/C02/C02_Wood.jpg')
  c02TextureWood.flipY = false
  c02TextureWood.colorSpace = THREE.SRGBColorSpace


  // //Opacity
  // const meshOpacity = 0.6


  // Floor 01
  const matc02Concrete = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c02TextureConcrete,
      toneMapped: false
    })
  }, [c02TextureConcrete])


  // Floor 01
  const matc02Floor = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c02TextureFloor,
      toneMapped: false
    })
  }, [c02TextureFloor])


  // Floor 01
  const matc02Frames = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c02TextureFrames,
      toneMapped: false
    })
  }, [c02TextureFrames])

  // Floor 01
  const matc02Wall = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c02TextureWall,
      toneMapped: false
    })
  }, [c02TextureWall])

  // Floor 01
  const matc02Wood = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c02TextureWood,
      toneMapped: false
    })
  }, [c02TextureWood])



  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.C02W_Concrete.geometry} 
        // material={materials.Concrete} 
        material={ matc02Concrete }
      >

        {/* <lineSegments scale={1.001}>
          <edgesGeometry args={[nodes.C02W_Concrete.geometry, Math.PI]} />
          <lineBasicMaterial 
            // color="#9B9B9B" 
            color="#C6C1AE"
            transparent 
            opacity={0.9} 
          />
        </lineSegments>  */}
      </mesh>
      <mesh 
        geometry={nodes.C02W_Floor.geometry} 
        // material={materials.Concrete} 
        material={ matc02Floor }
      >
        {/* <lineSegments scale={1.001}>
          <edgesGeometry args={[nodes.C02W_Floor.geometry, Math.PI]} />
          <lineBasicMaterial 
            // color="#9B9B9B" 
            color="#C6C1AE"
            transparent 
            opacity={0.9} 
          />
        </lineSegments>  */}
      </mesh>
      
      <mesh 
        geometry={nodes.C02W_Frames.geometry} 
        // material={materials.Wood} 
        material={ matc02Frames }
      />
      <mesh 
        geometry={nodes.C02W_Wall.geometry} 
        // material={materials.Wall} 
        material={ matc02Wall }
      >

        {/* <lineSegments scale={1.001}>
          <edgesGeometry args={[nodes.C02W_Wall.geometry, Math.PI]} />
          <lineBasicMaterial 
            // color="#9B9B9B" 
            color="#C6C1AE"
            transparent 
            opacity={0.9} 
          />
        </lineSegments>          */}
      </mesh>
      <mesh 
        geometry={nodes.C02W_Wood.geometry} 
        // material={materials.Wood} 
        material={ matc02Wood }
      />
    </group>
  )
}

useGLTF.preload('./models/Casona02.glb')

export default Casona02
