/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Casona03.glb 
*/

import React, { useMemo } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'

const Casona03 = (props) => {
  const { nodes, materials } = useGLTF('./models/Casona03.glb')


  // // Creamos el material solo una vez
  // const whiteTransparentMat = useMemo(() => {
  //   return new THREE.MeshStandardMaterial({
  //     color: '#FFFEF7',
  //     transparent: true,
  //     opacity: 0.8,
  //     // depthWrite: false,
  //   })
  // }, [])



  const c03TextureFloor = useTexture('./textures/C03/C03_Floor.jpg')
  c03TextureFloor.flipY = true
  c03TextureFloor.colorSpace = THREE.SRGBColorSpace
  
  const c03TextureFloor02 = useTexture('./textures/C03/C03_Floor02.jpg')
  c03TextureFloor02.flipY = false
  c03TextureFloor02.colorSpace = THREE.SRGBColorSpace

  const c03TextureFrames = useTexture('./textures/C03/C03_Frames.jpg')
  c03TextureFrames.flipY = false
  c03TextureFrames.colorSpace = THREE.SRGBColorSpace

  const c03TextureWall02 = useTexture('./textures/C03/C03_Wall02.jpg')
  c03TextureWall02.flipY = false
  c03TextureWall02.colorSpace = THREE.SRGBColorSpace

  const c03TextureRoof = useTexture('./textures/C03/C03_Roof.jpg')
  c03TextureRoof.flipY = false
  c03TextureRoof.colorSpace = THREE.SRGBColorSpace

  const c03TextureWall = useTexture('./textures/C03/C03_Wall.jpg')
  c03TextureWall.flipY = false
  c03TextureWall.colorSpace = THREE.SRGBColorSpace

  const c03TextureWood = useTexture('./textures/C03/C03_Wood.jpg')
  c03TextureWood.flipY = false
  c03TextureWood.colorSpace = THREE.SRGBColorSpace


  // //Opacity
  // const meshOpacity = 1.0

  
  // Floor 01
  const matFloor = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c03TextureFloor,
      toneMapped: false
    })
  }, [c03TextureFloor])


  // Floor 01
  const matFloor02 = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c03TextureFloor02,
      toneMapped: false
    })
  }, [c03TextureFloor02])

  // Floor 01
  const matFrames = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c03TextureFrames,
      toneMapped: false
    })
  }, [c03TextureFrames])

  // Floor 01
  const matWall02 = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c03TextureWall02,
      toneMapped: false
    })
  }, [c03TextureWall02])

  // Floor 01
  const matRoof = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c03TextureRoof,
      toneMapped: false
    })
  }, [c03TextureRoof])

  // Floor 01
  const matWall = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c03TextureWall,
      toneMapped: false
    })
  }, [c03TextureWall])

  // Floor 01
  const matWood = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c03TextureWood,
      toneMapped: false
    })
  }, [c03TextureWood])




  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.C03W_Floor.geometry} 
        // material={materials.Concrete}
        material={ matFloor }
      >
        {/* <lineSegments scale={1.001}>
          <edgesGeometry args={[nodes.C03W_Floor.geometry, Math.PI]} />
          <lineBasicMaterial 
            // color="#9B9B9B" 
            color="#C6C1AE"
            transparent 
            opacity={0.9} 
          />
        </lineSegments>  */}

      </mesh>

      <mesh 
        geometry={nodes.C03W_Floor02.geometry} 
        // material={materials.Concrete}
        material={ matFloor02 }
      >
        {/* <lineSegments scale={1.001}>
          <edgesGeometry args={[nodes.C03W_Floor02.geometry, Math.PI]} />
          <lineBasicMaterial 
            // color="#9B9B9B" 
            color="#C6C1AE"
            transparent 
            opacity={0.9} 
          />
        </lineSegments>  */}
      </mesh>

      <mesh 
        geometry={nodes.C03W_Frames.geometry} 
        // material={materials.Wood}
        material={ matFrames }
      />
      <mesh 
        geometry={nodes.C03W_Wall02.geometry} 
        // material={materials.Wood}
        material={ matWall02 }
      />
      <mesh 
        geometry={nodes.C03W_Roof.geometry} 
        // material={materials.Wall}
        material={ matRoof }
      >

        {/* <lineSegments scale={1.001}>
          <edgesGeometry args={[nodes.C03W_Roof.geometry, Math.PI * 2]} />
          <lineBasicMaterial 
            // color="#9B9B9B" 
            color="#C6C1AE"
            transparent 
            opacity={0.9} 
          />
        </lineSegments>  */}
      </mesh>
      <mesh 
        geometry={nodes.C03W_Wall.geometry} 
        // material={materials.Wall}
        material={ matWall }
      >

        {/* <lineSegments scale={1.001}>
          <edgesGeometry args={[nodes.C03W_Wall.geometry, Math.PI]} />
          <lineBasicMaterial 
            // color="#9B9B9B" 
            color="#C6C1AE"
            transparent 
            opacity={0.9} 
          />
        </lineSegments>  */}
      </mesh>
      <mesh 
        geometry={nodes.C03W_Wood.geometry} 
        // material={materials.Wood}
        material={ matWood }
      />
    </group>
  )
}

useGLTF.preload('./models/Casona03.glb')

export default Casona03
