/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Furniture.glb 
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Furniture = (props) => {
  const { nodes, materials } = useGLTF("./models/Furniture.glb");

  const furTextureWall = useTexture("./textures/FU/FU_Wall.jpg");
  furTextureWall.flipY = false;
  furTextureWall.colorSpace = THREE.SRGBColorSpace;

  const furTextureWood = useTexture("./textures/FU/FU_Wood.jpg");
  furTextureWood.flipY = false;
  furTextureWood.colorSpace = THREE.SRGBColorSpace;

  // Floor 01
  const furWall = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: furTextureWall,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [furTextureWall]);

  // Floor 01
  const furWood = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: furTextureWood,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [furTextureWood]);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.FU_Wall.geometry}
        // material={materials.Wall}
        material={furWall}
      ></mesh>

      <mesh
        geometry={nodes.FU_Wood.geometry}
        // material={materials.Wood}
        material={furWood}
      ></mesh>
    </group>
  );
};

useGLTF.preload("./models/Furniture.glb");

export default Furniture;
