/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Residencial02.glb 
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Residencial02 = (props) => {
  const { nodes, materials } = useGLTF("./models/Residencial02.glb");

  // // Creamos el material solo una vez
  // const whiteTransparentMat = useMemo(() => {
  //   return new THREE.MeshStandardMaterial({
  //     // color: '#EEE9B2',
  //     color: '#FFFEF7',
  //     transparent: true,
  //     opacity: 0.8,
  //     // depthWrite: false,
  //   })
  // }, [])

  const r02TextureFloorplates = useTexture(
    "./textures/R02/R02_Floorplates.jpg",
  );
  r02TextureFloorplates.flipY = false;
  r02TextureFloorplates.colorSpace = THREE.SRGBColorSpace;

  const r02TextureFrames = useTexture("./textures/R02/R02_Frames.jpg");
  r02TextureFrames.flipY = false;
  r02TextureFrames.colorSpace = THREE.SRGBColorSpace;

  const r02TextureWall = useTexture("./textures/R02/R02_Wall.jpg");
  r02TextureWall.flipY = false;
  r02TextureWall.colorSpace = THREE.SRGBColorSpace;

  const r02TextureWall02 = useTexture("./textures/R02/R02_Wall02.jpg");
  r02TextureWall02.flipY = false;
  r02TextureWall02.colorSpace = THREE.SRGBColorSpace;

  const r02TextureWood = useTexture("./textures/R02/R02_Wood.jpg");
  r02TextureWood.flipY = false;
  r02TextureWood.colorSpace = THREE.SRGBColorSpace;

  // //Opacity
  // const meshOpacity = 1.0

  // Floor 01
  const matFloorplates = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: r02TextureFloorplates,
      toneMapped: false,
    });
  }, [r02TextureFloorplates]);

  // Floor 01
  const matFrames = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: r02TextureFrames,
      toneMapped: false,
    });
  }, [r02TextureFrames]);

  // Floor 01
  const matWall = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: r02TextureWall,
      toneMapped: false,
    });
  }, [r02TextureWall]);

  // Floor 01
  const matWall02 = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: r02TextureWall02,
      toneMapped: false,
    });
  }, [r02TextureWall02]);

  // Floor 01
  const matWood = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: r02TextureWood,
      toneMapped: false,
    });
  }, [r02TextureWood]);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.R02W_Floorplates.geometry}
        // material={materials.Concrete}
        material={matFloorplates}
      >
        {/* <lineSegments scale={1.001}>
          <edgesGeometry args={[nodes.R02W_Floorplates.geometry, Math.PI]} />
          <lineBasicMaterial 
            // color="#9B9B9B" 
            color="#C6C1AE"
            transparent 
            opacity={0.9} 
          />
        </lineSegments>  */}
      </mesh>

      <mesh
        geometry={nodes.R02W_Frames.geometry}
        // material={materials.Wood}
        material={matFrames}
      />
      <mesh
        geometry={nodes.R02W_Wall.geometry}
        // material={materials.Wall}
        material={matWall}
      >
        {/* <lineSegments scale={1.001}>
          <edgesGeometry args={[nodes.R02W_Wall.geometry, Math.PI]} />
          <lineBasicMaterial 
            // color="#9B9B9B" 
            color="#C6C1AE"
            transparent 
            opacity={0.9} 
          />
        </lineSegments>  */}
      </mesh>

      <mesh
        geometry={nodes.R02W_Wall02.geometry}
        // material={materials.Wood}
        material={matWall02}
      />
      <mesh
        geometry={nodes.R02W_Wood.geometry}
        // material={materials.Wood}
        material={matWood}
      >
        {/* <lineSegments scale={1.001}>
          <edgesGeometry args={[nodes.R02W_Wood.geometry, Math.PI]} />
          <lineBasicMaterial 
            // color="#4B4B4B"
            // color="#9B9B9B" 
            color="#C6C1AE"
            transparent 
            opacity={0.9} 
          />
        </lineSegments>  */}
      </mesh>
    </group>
  );
};

useGLTF.preload("./models/Residencial02.glb");

export default Residencial02;
