/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Residencial03.glb 
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Residencial03 = (props) => {
  const { nodes, materials } = useGLTF("./models/Residencial03.glb");

  const r03TextureFloorplates = useTexture(
    "./textures/R03/R03_Floorplates.jpg",
  );
  r03TextureFloorplates.flipY = false;
  r03TextureFloorplates.colorSpace = THREE.SRGBColorSpace;

  const r03TextureFrames = useTexture("./textures/R03/R03_Frames.jpg");
  r03TextureFrames.flipY = false;
  r03TextureFrames.colorSpace = THREE.SRGBColorSpace;

  const r03TextureWall = useTexture("./textures/R03/R03_Wall.jpg");
  r03TextureWall.flipY = false;
  r03TextureWall.colorSpace = THREE.SRGBColorSpace;

  const r03TextureWall02 = useTexture("./textures/R03/R03_Wall02.jpg");
  r03TextureWall02.flipY = false;
  r03TextureWall02.colorSpace = THREE.SRGBColorSpace;

  const r03TextureWood = useTexture("./textures/R03/R03_Wood.jpg");
  r03TextureWood.flipY = false;
  r03TextureWood.colorSpace = THREE.SRGBColorSpace;

  // Floor 01
  const r03Floorplates = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: r03TextureFloorplates,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [r03TextureFloorplates]);

  // Floor 01
  const r03Frames = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: r03TextureFrames,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [r03TextureFrames]);

  // Floor 01
  const r03Wall = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: r03TextureWall,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [r03TextureWall]);

  // Floor 01
  const r03Wall02 = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: r03TextureWall02,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [r03TextureWall02]);

  // Floor 01
  const r03Wood = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: r03TextureWood,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [r03TextureWood]);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.R03W_Frames.geometry}
        // material={materials.Wood}
        material={r03Frames}
      >
        {/* <meshBasicMaterial map={ r03TextureFrames } /> */}
      </mesh>
      <mesh
        geometry={nodes.R03W_Florplates.geometry}
        // material={materials.Concrete}
        material={r03Floorplates}
      >
        {/* <meshBasicMaterial map={ r03TextureFloorplates } /> */}
      </mesh>
      <mesh
        geometry={nodes.R03W_Wall.geometry}
        // material={materials.Wall}
        material={r03Wall}
      >
        {/* <meshBasicMaterial map={ r03TextureWall } /> */}
      </mesh>
      <mesh
        geometry={nodes.R03W_Wall02.geometry}
        // material={materials.Wood}
        material={r03Wall02}
      >
        {/* <meshBasicMaterial map={ r03TextureWall02 } /> */}
      </mesh>
      <mesh
        geometry={nodes.R03W_Wood.geometry}
        // material={materials.Wood}
        material={r03Wood}
      >
        {/* <meshBasicMaterial map={ r03TextureWood } /> */}
      </mesh>
    </group>
  );
};

useGLTF.preload("./models/Residencial03.glb");

export default Residencial03;
