/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Residencial01.glb 
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Residencial01 = (props) => {
  const { nodes, materials } = useGLTF("./models/Residencial01.glb");

  const r01TextureFloorplates = useTexture(
    "./textures/R01/R01_Floorplates.jpg",
  );
  r01TextureFloorplates.flipY = false;
  r01TextureFloorplates.colorSpace = THREE.SRGBColorSpace;

  const r01TextureFrames = useTexture("./textures/R01/R01_Frames.jpg");
  r01TextureFrames.flipY = false;
  r01TextureFrames.colorSpace = THREE.SRGBColorSpace;

  const r01TextureWall = useTexture("./textures/R01/R01_Wall.jpg");
  r01TextureWall.flipY = false;
  r01TextureWall.colorSpace = THREE.SRGBColorSpace;

  const r01TextureWall02 = useTexture("./textures/R01/R01_Wall02.jpg");
  r01TextureWall02.flipY = false;
  r01TextureWall02.colorSpace = THREE.SRGBColorSpace;

  const r01TextureWood = useTexture("./textures/R01/R01_Wood.jpg");
  r01TextureWood.flipY = false;
  r01TextureWood.colorSpace = THREE.SRGBColorSpace;

  // Floor 01
  const r01Floorplates = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: r01TextureFloorplates,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [r01TextureFloorplates]);

  // Floor 01
  const r01Frames = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: r01TextureFrames,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [r01TextureFrames]);

  // Floor 01
  const r01Wall = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: r01TextureWall,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [r01TextureWall]);

  // Floor 01
  const r01Wall02 = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: r01TextureWall02,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [r01TextureWall02]);

  // Floor 01
  const r01Wood = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: r01TextureWood,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [r01TextureWood]);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.R01W_Floorplates.geometry}
        // material={materials.Concrete}
        material={r01Floorplates}
        position={[0, 0.05, 0]}
      >
        {/* <meshBasicMaterial map={ r01TextureFloorplates } /> */}
      </mesh>
      <mesh
        geometry={nodes.R01W_Frames.geometry}
        // material={materials.Wood}
        material={r01Frames}
        position={[0, 0.05, 0]}
      >
        {/* <meshBasicMaterial map={ r01TextureFrames } /> */}
      </mesh>
      <mesh
        geometry={nodes.R01W_Walls.geometry}
        // material={materials.Wall}
        material={r01Wall}
        position={[0, 0.05, 0]}
      >
        {/* <meshBasicMaterial map={ r01TextureWall } /> */}
      </mesh>
      <mesh
        geometry={nodes.R01W_Walls02.geometry}
        // material={materials.Wood}
        material={r01Wall02}
        position={[0, 0.05, 0]}
      >
        {/* <meshBasicMaterial map={ r01TextureWall02 } /> */}
      </mesh>
      <mesh
        geometry={nodes.R01W_Wood.geometry}
        // material={materials.Wood}
        material={r01Wood}
        position={[0, 0.05, 0]}
      >
        {/* <meshBasicMaterial map={ r01TextureWood } /> */}
      </mesh>
    </group>
  );
};

useGLTF.preload("./models/Residencial01.glb");

export default Residencial01;
