/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Talud.glb 
*/

import React, { useMemo } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'

const Talud = (props) => {
  const { nodes, materials } = useGLTF('./models/Talud.glb')


  const taTextureFloor = useTexture('./textures/TA/TA_Floor.jpg')
  taTextureFloor.flipY = false
  taTextureFloor.colorSpace = THREE.SRGBColorSpace

  const taTextureWall = useTexture('./textures/TA/TA_Wall.jpg')
  taTextureWall.flipY = false
  taTextureWall.colorSpace = THREE.SRGBColorSpace

  const taTextureGround02 = useTexture('./textures/TA/TA_Ground02.jpg')
  taTextureGround02.flipY = false
  taTextureGround02.colorSpace = THREE.SRGBColorSpace

  const taTextureCasona03 = useTexture('./textures/TA/TA_CA_Extra.jpg')
  taTextureCasona03.flipY = false
  taTextureCasona03.colorSpace = THREE.SRGBColorSpace

  const taTextureGround01 = useTexture('./textures/TA/TA_Ground01.jpg')
  taTextureGround01.flipY = false
  taTextureGround01.colorSpace = THREE.SRGBColorSpace




  // Floor 01
  const taFloor = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: taTextureFloor,
      toneMapped: false            // prevent threejs from washing colors
    })
  }, [taTextureFloor])

  // Floor 01
  const taWall = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: taTextureWall,
      toneMapped: false            // prevent threejs from washing colors
    })
  }, [taTextureWall])

  // Floor 01
  const taGround02 = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: taTextureGround02,
      toneMapped: false            // prevent threejs from washing colors
    })
  }, [taTextureGround02])

  // Floor 01
  const taCasona03 = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: taTextureCasona03,
      toneMapped: false            // prevent threejs from washing colors
    })
  }, [taTextureCasona03])

  // Floor 01
  const taGround01 = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: taTextureGround01,
      toneMapped: false            // prevent threejs from washing colors
    })
  }, [taTextureGround01])



  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.TA_Floor.geometry} 
        // material={materials.Concrete} 
        material={taFloor} 
      >

      </mesh>

      <mesh 
        geometry={nodes.TA_Wall.geometry} 
        // material={materials.Wall} 
        material={taWall} 
      >

      </mesh>

      <mesh 
        geometry={nodes.TA_Ground02.geometry} 
        // material={materials.Ground_02} 
        material={taGround02} 
      >

      </mesh>
      <mesh 
        geometry={nodes.TA_Casona03_Extra.geometry} 
        // material={materials['Wood.006']} 
        material={taCasona03} 
      >

      </mesh>
      <mesh 
        geometry={nodes.TA_Ground01.geometry} 
        // material={materials.Ground01} 
        material={taGround01} 
      >

      </mesh>
    </group>
  )
}

useGLTF.preload('./models/Talud.glb')

export default Talud
