/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

import { isMobileAtom } from "../UI";
import { useAtom } from "jotai";

const Terreno = (props) => {
  const { nodes, materials } = useGLTF("./models/Terreno.glb");

  const [isMobile] = useAtom(isMobileAtom);

  const terrainTexture = useTexture(
    isMobile
      ? "./textures/TT/TT_Terrain04.jpg"
      : "./textures/TT/TT_Terrain02.jpg",
  );

  terrainTexture.flipY = false;

  // VERY IMPORTANT ↓
  terrainTexture.colorSpace = THREE.SRGBColorSpace;

  const terrainFloor = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: terrainTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [terrainTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_1.geometry}
        // material={nodes.Object_1.material}
        material={terrainFloor}
      />
    </group>
  );
};

useGLTF.preload("./models/Terreno.glb");

export default Terreno;
